Update man page. Fix man page install targets

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -225,6 +225,7 @@ ifeq ($(DETECTED_OS),Windows)
 INSTALL_DIR=C:/Program\ Files
 else
 INSTALL_DIR=/usr/local
+MAN_DIR=$(INSTALL_DIR)/share/man/man1
 endif
 
 print-vars:
@@ -259,6 +260,16 @@ else
 	install -m 644 ./util/*.hpp $(INSTALL_DIR)/include/kanzi/util
 	install -d $(INSTALL_DIR)/bin
 	install -m577 ../bin/$(APP)$(PROG_SUFFIX) $(INSTALL_DIR)/bin
+	install -d $(MAN_DIR)
+	if [ -f ../kanzi.1.gz ]; then \
+		install -m 644 ../kanzi.1.gz $(MAN_DIR)/$(APP).1.gz; \
+	elif [ -f ../kanzi.1 ]; then \
+		gzip -n -c ../kanzi.1 > $(MAN_DIR)/$(APP).1.gz; \
+		chmod 644 $(MAN_DIR)/$(APP).1.gz; \
+	else \
+		echo "Error: missing ../kanzi.1.gz or ../kanzi.1"; \
+		exit 1; \
+	fi
 endif
 
 # Uninstall may require sudo or admin rights
@@ -272,6 +283,7 @@ else
 	rm -f $(INSTALL_DIR)/bin/$(APP_STATIC)$(PROG_SUFFIX)
 	rm -f $(INSTALL_DIR)/bin/$(APP_DYNAMIC)$(PROG_SUFFIX)
 	rm -f $(INSTALL_DIR)/bin/$(APP)$(PROG_SUFFIX)
+	rm -f $(MAN_DIR)/$(APP).1.gz
 endif
 
 clean:
